version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    container_name: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  localai:
    image: localai/localai:latest
    container_name: localai-server
    ports:
      - "${LOCALAI_PORT}:8080"
    environment:
      - DEBUG=true
      - MODELS_PATH=/models/mistral
    volumes:
      - ./models:/models
    command: ["/usr/bin/local-ai", "--config-file", "/models/mistral/config.yaml"]
    restart: unless-stopped
volumes:
  localai_models:
    driver: local
